name: CurrencyFetcherBuild

trigger:
    branches:
        include:
            - main
variables:
    REPOSITORY_NAME: currency_fetcher

    
stages:
    - stage: Build
      jobs:
          - job: BuildAndPushImage
            pool: Azure Pipelines
            steps:
                            
            - task: Bash@3
              displayName: CreatingTag
              inputs:
                targetType: 'inline'
                script: |
                    GIT_COMMIT=$(git rev-parse --short HEAD)
                    echo "GIT_COMMIT: ${GIT_COMMIT}"
                    echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"

            - script: docker build -f  infra/Docker/CurrencyFetcher.Dockerfile -t $(REPOSITORY_NAME):$(GIT_COMMIT) .
              displayName: BuildImage
              
            - task: ECRPushImage@1
              displayName: PushingImageToECR
              inputs:
                awsCredentials: aws_ecr
                regionName: us-east-1
                imageSource: 'imageid'
                sourceImageId: '$(REPOSITORY_NAME):$(GIT_COMMIT)'
                repositoryName: '$(REPOSITORY_NAME)'
                pushTag: '$(GIT_COMMIT)'
          
          - job: GitTea
            pool: Docker
            steps:
              
              - task: Bash@3
                displayName: giteaKeyPrep
                inputs:
                  targetType: 'inline'
                  script: |
                    mkdir -p ~/.ssh
                    echo "$(gitea_key)" > ~/.ssh/id_ed25519
                    chmod 600 ~/.ssh/id_ed25519

              
              - task: Bash@3
                displayName: giteaKeyPrep
                inputs:
                  targetType: 'inline'
                  script: |
                    git config --global user.email "$(gitea_mail)"
                    git config --global user.name "$(gitea_name)"
                    git push origin main




