name: CurrencyFetcherBuild

trigger:
    branches:
        include:
            - main
          
    paths:
      include:
        - currency_fetcher/*
        - infra/AzureDevops/*
        - infra/Docker/*
        - infra/helm/CurrencyFetcher/*

variables:
    REPOSITORY_NAME: currency_fetcher

    
stages:
    - stage: Build
      jobs:
          # - job: BuildAndPushImage
          #   pool: Azure Pipelines
          #   steps:
                            
          #   - task: Bash@3
          #     displayName: CreatingTag
          #     inputs:
          #       targetType: 'inline'
          #       script: |
          #           GIT_COMMIT=$(git rev-parse --short HEAD)
          #           echo "GIT_COMMIT: ${GIT_COMMIT}"
          #           echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"

          #   - script: docker build -f  infra/Docker/CurrencyFetcher.Dockerfile -t $(REPOSITORY_NAME):$(GIT_COMMIT) .
          #     displayName: BuildImage
              
          #   - task: ECRPushImage@1
          #     displayName: PushingImageToECR
          #     inputs:
          #       awsCredentials: aws_ecr
          #       regionName: us-east-1
          #       imageSource: 'imageid'
          #       sourceImageId: '$(REPOSITORY_NAME):$(GIT_COMMIT)'
          #       repositoryName: '$(REPOSITORY_NAME)'
          #       pushTag: '$(GIT_COMMIT)'
          
          - job: GitTea
            pool: Docker
            workspace:
              clean: all
            steps:
              
              - task: Bash@3
                displayName: installDependency
                inputs: 
                 targetType: inline
                 script: |
                  apt install openssh-client -y


              - task: DownloadSecureFile@1
                displayName: GettingGiteaCert
                name: gitea_token
                inputs:
                  secureFile: 'gitea_token'
                
              - task: Bash@3
                displayName: giteaKeyPrep
                inputs:
                  targetType: 'inline'
                  script: |
                    mkdir -p ~/.ssh
                    cat "$(gitea_token.secureFilePath)" > ~/.ssh/id_ed25519
                    chmod 600 ~/.ssh/id_ed25519
                    ssh-keyscan -p $(gitea_server_port) -t ed25519 $(gitea_server) >> ~/.ssh/known_hosts


              - task: Bash@3
                displayName: updateRepo
                inputs:
                  targetType: 'inline'
                  script: |
                    git fetch --all
                    git remote add gitea $(gitea_remote_repo)
                    for remote_branch in $(git branch -r | grep 'origin/'); do
                      branch_name=$(echo "$remote_branch" | sed 's/origin\///')
                      git checkout "$branch_name"
                      git pull origin "$branch_name"
                      git pull gitea "$branch_name"

                    done

              
              - task: Bash@3
                displayName: pushRepo
                inputs:
                  targetType: 'inline'
                  script: |
                    git config --global user.email "$(gitea_mail)"
                    git config --global user.name "$(gitea_name)"
                    git push gitea --all





